### ISSUE TITLE
Misspelling

### ISSUE THREAD

**Issue by drbyte** [bislewl/zencart_Spee-Dee-Delivery#1]
The main foldername in this package is named SpeeDee `Deilvery`.  Shouldn't that be `Delivery` ?

**Comment by bislewl** [comment]
Thanks! Fixed. How'd you know there was a repo for it?

**Comment by drbyte** [comment]
Saw it here on github :)

**Comment by bislewl** [comment]
ohh I thought you finally caught me red handed :)
https://github.com/bislewl/zencart_Spee-Dee-Delivery/blob/master/SpeeDee%20Deilvery/zencart_plugin.json
I'v been adding these to my module so it's easier for those moderating to see changes...I suppose I shouldn't do that??
